### ISSUE TITLE
Policy

### ISSUE THREAD

**Issue by ragneoitspuu** [HL7EE/ig-ee-base#12]
1. Lisada Policysse mustSupporti kirjeldus.
2. [Naming ](https://build.fhir.org/ig/HL7EE/ig-ee-base/policy.html#naming) - siit on osad reeglid puudu, mis on [R4-s](https://simplifier.net/guide/ee-fhir-base/Home/Policy/Policy-Index?version=current#Naming) olemas.

**Comment by KristiinaKuldkepp** [comment]
Selline kirjeldus oli meil Guidances: 
According to the "open-world" model it is best to approach changing the cardinalities with caution. This is due to the fact that in derived profiles, cardinalities could be restricted only, but not widened. To make EEBase profiles as flexible as possible, the developers of EEBase followed the principle where most of the cardinalities were left as in the FHIR specification.
When an element is mandatory in FHIR specification then EEBase will add a must support flag to it. This means that the future profiles derived from EEBase SHALL use this element in their profiles.... 

(natuke vajab veel lisa)

**Comment by ragneoitspuu** [comment]
> Selline kirjeldus oli meil Guidances: According to the "open-world" model it is best to approach changing the cardinalities with caution. This is due to the fact that in derived profiles, cardinalities could be restricted only, but not widened. To make EEBase profiles as flexible as possible, the developers of EEBase followed the principle where most of the cardinalities were left as in the FHIR specification. When an element is mandatory in FHIR specification then EEBase will add a must support flag to it. This means that the future profiles derived from EEBase SHALL use this element in their profiles....
> 
> (natuke vajab veel lisa)

Ma panin selle lõigu Home lehele Scope alapeatüki alla.

**Comment by igorboss** [comment]
1 ja 2 tehtud
